---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: triton-models
  namespace: temporal-workers
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: "efs-sc"
  resources:
    requests:
      storage: 5Gi
